Update hypre version
ECP-copa/Cabana pull request #446
Opened 2021-08-24 20:06 UTC by streeve

Remove workaround with new tagged release

Fixes #431

2021-08-24 20:22 UTC, junghans approved these changes

2021-09-03 13:49 UTC, dalg24 requested changes
Drop debug print statements

2021-09-03 13:49 UTC, dalg24 commented on CMakeLists.txt
> +message("Debug ${HYPRE_DIR}")
Remove

2021-09-03 13:49 UTC, dalg24 commented on docker/Dockerfile
> +    cat /opt/hypre/lib/cmake/HYPRE/HYPREConfig.cmake && \
Remove

2021-09-03 13:55 UTC, dalg24 commented
For reference
https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Cabana/detail/PR-446/7/pipeline#step-48-log-976

2021-09-03 13:59 UTC, junghans commented
@dalg24 calm yourself, we are still debugging this.....

2021-09-03 14:03 UTC, dalg24 commented
> @dalg24 calm yourself, we are still debugging this.....

Got it :)

This is weird indeed.  The link I posted is to you debug prints.  `HYPRE_WITH_MPI` is `TRUE`.  Do you know how to make the `find_dependency(MPI ...)` verbose to make sure it does not bypass it with our having already found MPI?

2021-09-03 14:05 UTC, dalg24 commented
(I blocked to make sure auto-merge does not happen)

2021-09-03 15:31 UTC, junghans approved these changes

2021-09-03 15:33 UTC, junghans commented
@sslattery @dalg24 @streeve turns out this was a bug in CMake, bumping it to 3.16 helped. 
Current Kokkos master requires 3.16 as well, so not a great restriction, as we will require kokkos-3.3 at some point anyhow.

2021-09-03 18:34 UTC, dalg24 commented
> @sslattery @dalg24 @streeve turns out this was a bug in CMake, bumping it to 3.16 helped.
> Current Kokkos master requires 3.16 as well, so not a great restriction, as we will require kokkos-3.3 at some point anyhow.

Is it FindMPI module bug in older versions as I suspected earlier on the phone?

2021-09-03 20:07 UTC, dalg24 approved these changes

2021-09-03 20:08 UTC, dalg24 commented
We need to bump our cmake requirement on a follow up pr

2021-09-03 20:11 UTC, junghans commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.16)
@dalg24 I bumped it here.

2021-09-03 21:26 UTC, merged