Add cajita examples
ECP-copa/Cabana pull request #504
Opened 2022-03-03 17:25 UTC by streeve

Only folder structure so far

Part of #352

2022-03-17 22:41 UTC, sslattery requested changes

2022-03-17 22:41 UTC, sslattery commented on example/cajita_tutorial/07_local_mesh/local_mesh_example.cpp
> +      necessary information from the local mesh.
necessary information from the local mesh including ghost information.

2022-03-17 22:41 UTC, sslattery commented on example/cajita_tutorial/07_local_mesh/local_mesh_example.cpp
> +    // Create the local mesh from the local grid.
The `device_type` template indicates which memory and execution spaces will be able to access the resulting local mesh data structure.

2022-03-17 22:41 UTC, sslattery commented on example/cajita_tutorial/07_local_mesh/local_mesh_example.cpp
> +      often be in a Kokkos parallel kernel.
I would point out that the local mesh object is designed such that it can be captured by value in a Kokkos parallel loop

2022-03-17 22:41 UTC, sslattery commented on example/cajita_tutorial/08_array/array_example.cpp
> +      An array layout includes the local grid size information together with the
An array layout includes the local grid size information together with the, the number of values per mesh entity in the field (dimensionality), and the entity type on which the field is defined. An array may only be defined on a single entity type.

2022-03-17 22:41 UTC, sslattery commented on example/cajita_tutorial/08_array/array_example.cpp
> +      Similar to the local grid, the array layout holds index spaces for
Note that index spaces generated by array layouts have an additional dimension over the field values on each entity.

2022-03-17 22:41 UTC, sslattery commented on example/cajita_tutorial/08_array/array_example.cpp
> +    // Now make a clone and copy.
Cloning an array makes a new, identical array to the given array with a new memory allocation.

2022-03-23 20:55 UTC, streeve commented
Thanks for the review @sslattery. I believe everything is addressed in the last commit. @abisner @kwitaechong if you can take a quick look as well, let me know if you have suggestions

2022-03-25 21:56 UTC, sslattery approved these changes

2022-03-25 22:00 UTC, streeve commented
Pushed only to remove the unfinished example folders. No changes to content

2022-03-25 23:07 UTC, merged