Add Splines of order 4 - 7
ECP-copa/Cabana pull request #800
Opened 2024-11-05 14:35 UTC by rodrigoacb

This commits add BSplines of order 4 to 7 following the polynomial definitions on deserno1998 [1]

Following @streeve request,  PR #799  is now split into two PRs and once merged, this one will only show diff changes related to Splines.

This changes were done in cooperation with @rhalver 

[1] Markus Deserno, Christian Holm; How to mesh up Ewald sums. I. A theoretical and numerical comparison of various particle mesh routines. J. Chem. Phys. 8 November 1998; 109 (18): 7678–7693. https://doi.org/10.1063/1.477414

2024-11-12 14:27 UTC, streeve commented
@lebuller can you take a look at the spline updates here? @rodrigoacb probably easiest to rebase out all but the first commit

2024-11-12 15:16 UTC, rodrigoacb commented
> @lebuller can you take a look at the spline updates here? @rodrigoacb probably easiest to rebase out all but the first commit

Thanks @streeve Sam. I rebased onto the first commit and kept the clang-format commit since lt changed files related to this pr

2024-12-06 16:30 UTC, streeve commented
ping @lebuller

2025-01-16 15:10 UTC, junghans commented
Any updates on this?

2025-01-16 15:26 UTC, lebuller commented
> Any updates on this?

Sorry, started reviewing this before holidays and fell of my radar after. Will get back to it at the start of next week

2025-01-27 17:04 UTC, lebuller requested changes

2025-01-27 17:04 UTC, lebuller commented on grid/src/Cabana_Grid_Splines.hpp
> +        values[0] =
Clean up the formatting on this so it is easier to read. Using the pre-calcuated powers of xn as mentioned above should help

2025-01-27 17:04 UTC, lebuller commented on grid/src/Cabana_Grid_Splines.hpp
> +        xn -= 0.5;
Same as above, pre-calculate the powers of `xn` to prevent recomputing the values for each gradient and cleanup the formatting using the precomputed values

2025-01-27 17:04 UTC, lebuller commented on grid/src/Cabana_Grid_Splines.hpp
> +        values[0] =
Same as for quartic values. Precompute the powers of `xn` and change formatting to improve readability of the calls for `values[n]=`

2025-01-27 17:04 UTC, lebuller commented on grid/src/Cabana_Grid_Splines.hpp
> +        Scalar xn = x0 - static_cast<int>( x0 );
Same as for quartic values. Precompute the powers of `xn` and change formatting to improve readability of the calls for `values[n]=`

2025-01-27 17:04 UTC, lebuller commented on grid/src/Cabana_Grid_Splines.hpp
> +        Scalar xn = x0 - static_cast<int>( x0 );
Same as for quartic values. Precompute the powers of `xn` and change formatting to improve readability of the calls for `values[n]=`

2025-01-27 17:04 UTC, lebuller commented on grid/src/Cabana_Grid_Splines.hpp
> +        xn -= 0.5;
Same as for quartic values. Precompute the powers of `xn` and change formatting to improve readability of the calls for `values[n]=`

2025-02-17 13:54 UTC, rodrigoacb commented on grid/src/Cabana_Grid_Splines.hpp
> +        Scalar xn = x0 - static_cast<int>( x0 );
Hi @lebuller Lance, thank you for reviewing the implementation! We will take a look at the pre-calculation of xn powers and clean up the formatting.

2025-02-21 10:58 UTC, rodrigoacb commented
Hi @lebuller Lance, with this commit I have pre-computed the even powers of xn and followed the format from the cubic spline implementation. Odd powers are calculated as  xn * xn2 and xn * xn4.

I believe the compiler should already optimize this. In any case, if you prefer that odd powers are also pre-computed, please let me know.

2025-02-21 16:34 UTC, lebuller approved these changes
Looks good to me, good to merge when CI passes

2025-02-21 16:42 UTC, streeve commented
Thanks for the contribution, @rodrigoacb !

2025-02-21 16:42 UTC, merged